"""Support for Honeywell's RAMSES II protocol."""
DOMAIN = "evohome_cc"

STORAGE_VERSION = 1
STORAGE_KEY = DOMAIN

ATTR_HEAT_DEMAND = "heat_demand"
ATTR_SETPOINT = "setpoint"
ATTR_TEMPERATURE = "temperature"

ATTR_ACTUATOR_STATE: str = "actuator_enabled"
ATTR_BATTERY_STATE: str = "battery_state"
ATTR_WINDOW_STATE: str = "window_state"

BINARY_SENSOR_ATTRS = (ATTR_ACTUATOR_STATE, ATTR_BATTERY_STATE, ATTR_WINDOW_STATE)
SENSOR_ATTRS = (ATTR_HEAT_DEMAND, ATTR_TEMPERATURE)
